server:
  shutdown: graceful
spring:
  application:
    name: openshift-demo
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true